language: node_js
node_js:
  - "4.1"
  - "4.0"
sudo: false
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.4.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.0.4/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.4 && cat ./coverage/lcov.info | coveralls"
